/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-06-06 17:13:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BAValidation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("\t<title>Education Solution Builder SDI Tool box</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/sdi_toolbox.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container well crud-pannel\" id=\"crearProducto\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 well h2bg\" id=\"form-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"myfcc-jumbo-h2\">Business Account Validation</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<form id=\"create-product-form\" name=\"create-product-form\" action=\"crearproducto\" class=\"fcc-form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"_nombre\" type=\"text\" class=\"form-control\" placeholder=\"Nombre del producto\" name=\"_nombre\" required autofocus>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea cols=\"30\" rows=\"6\" id=\"_descripcion\"  class=\"form-control\" placeholder=\"Descripcion del producto\" name=\"_descripcion\" form=\"create-product-form\" required=\"true\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div  class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"_precio\" type=\"text\" class=\"form-control\" placeholder=\"Precio del producto MXN\" name=\"_precio\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"_categoria\"  type=\"text\" class=\"form-control\" placeholder=\"Categoria del producto\" name=\"_categoria\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div  class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea cols=\"30\" rows=\"6\" id=\"_detalles\"  class=\"form-control\" placeholder=\"Detalles del producto\" name=\"_detalles\" form=\"create-product-form\" required=\"true\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div  class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea cols=\"30\" rows=\"6\" id=\"_reviews\"  class=\"form-control\" placeholder=\"Reviews acerca del producto\" name=\"_reviews\" form=\"create-product-form\" required=\"true\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div  class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"_size\" class=\"form-control\" name=\"_size\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
for(int i=1; i<20; i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( i);
      out.write('"');
      out.write('>');
      out.print( i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div  class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"_color\" type=\"text\" class=\"form-control\" placeholder=\"Color(es) del producto\" name=\"_color\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div  class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"product_photos[]\" id=\"product_photos[]\" multiple >\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group checkbox fcc-pane-sm\" id=\"continue-registration\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"_continue-registration\" class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"_continue-registration\" type=\"checkbox\" value=\"1\" name=\"_continue-registration\" required=\"false\">Deseo registrar mas productos.</input>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><button id=\"_clear-form\" class=\"btn btn-danger btn-large\" type=\"reset\" value=\"Limpiar formulario\" text=\"Limpiar formulario\">Limpiar formulario</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"_register-product\" class=\"btn btn-success btn-large\" type=\"submit\"value=\"Registrar Producto\">Registrar Producto</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script src=\"js/jquery-1.11.3.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/validate/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/validate/dist/additional-methods.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/myfcc-js.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
